"""
Google Calendar integration for Whispr.

Fetches events for a given date using OAuth2 credentials.
Requires token.json to be present (generated by get_token.py).

Usage:
    python gcalendar.py
"""

from __future__ import annotations

import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import pytz
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

from connectonion import Agent

TOKEN_FILE = Path(__file__).resolve().parent / "token.json"
SCOPES = ["https://www.googleapis.com/auth/calendar.readonly"]


# =========================================================
# Auth
# =========================================================

def get_credentials() -> Credentials:
    creds = None

    if TOKEN_FILE.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

    # Refresh if expired
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
        TOKEN_FILE.write_text(creds.to_json(), encoding="utf-8")

    if not creds or not creds.valid:
        raise RuntimeError(
            "No valid credentials found. Run get_token.py first to authenticate."
        )

    return creds


# =========================================================
# Date extraction via agent
# =========================================================

def extract_date_from_text(text: str) -> str:
    """Use agent to extract the intended date from transcribed text.

    Returns 'today', 'tomorrow', or a date string like '2026-03-26'.
    """
    agent = Agent(
        model="gpt-5",
        name="whispr_date_extractor",
        system_prompt=(
            "You extract a date reference from transcribed speech. "
            "Return only one of: 'today', 'tomorrow', or a date in YYYY-MM-DD format. "
            "If no date is mentioned, return 'today'. "
            "No explanation, no punctuation, just the date string."
        )
    )
    result = str(agent.input(text)).strip()
    return result if result else "today"


# =========================================================
# Schedule fetcher
# =========================================================

def get_schedule(date: str = "today", timezone: str = "Australia/Sydney") -> str:
    try:
        creds = get_credentials()
        service = build("calendar", "v3", credentials=creds)

        tz = pytz.timezone(timezone)
        now = datetime.now(tz)

        if date == "today":
            target = now
        elif date == "tomorrow":
            target = now + timedelta(days=1)
        else:
            try:
                parsed = datetime.strptime(date, "%Y-%m-%d")
                target = tz.localize(parsed)
            except ValueError:
                target = now

        start = target.replace(hour=0, minute=0, second=0, microsecond=0).isoformat()
        end   = target.replace(hour=23, minute=59, second=59, microsecond=0).isoformat()

        # Get all calendars
        calendars = service.calendarList().list().execute().get("items", [])

        all_events = []
        for cal in calendars:
            cal_id = cal["id"]
            cal_name = cal.get("summary", cal_id)

            events = service.events().list(
                calendarId=cal_id,
                timeMin=start,
                timeMax=end,
                singleEvents=True,
                orderBy="startTime",
            ).execute().get("items", [])

            for event in events:
                event["_calendar_name"] = cal_name  # tag which calendar it came from
                all_events.append(event)

        # Sort all events by start time
        all_events.sort(key=lambda e: e["start"].get("dateTime", e["start"].get("date", "")))

        if not all_events:
            return f"No events found for {date}."

        lines = [f"Schedule for {date}:"]
        for event in all_events:
            start_raw = event["start"].get("dateTime", event["start"].get("date", ""))
            summary = event.get("summary", "Untitled event")
            cal_name = event.get("_calendar_name", "")

            try:
                dt = datetime.fromisoformat(start_raw)
                time_str = dt.strftime("%I:%M %p")
            except Exception:
                time_str = start_raw

            lines.append(f"  - {time_str}: {summary} [{cal_name}]")

        return "\n".join(lines)

    except Exception as e:
        return f"Could not fetch calendar: {str(e)}"

# =========================================================
# CLI test
# =========================================================

if __name__ == "__main__":
    date_arg = sys.argv[1] if len(sys.argv) > 1 else "today"
    print(get_schedule(date=date_arg))